{"uuid": "371c31cf-dbe2-4bdc-9e30-070528e1a72d", "children": ["020f4e52-6d35-4f56-a4cc-771459d5f338"], "befores": [{"name": "test_share_friend_boost", "status": "failed", "statusDetails": {"message": "AssertionError: 接口的返回码：【-1】，接口返回的信息：share_discount.error.boost_limit_once\nassert False is True\n +  where False = <class 'core.result_base.ResultBase'>.success\n", "trace": "  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 794, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/apple/Documents/atong/pythontest/pytestDemo/testcases/api_test/test_08_shere_discount.py\", line 25, in test_share_friend_boost\n    assert result.success is True, result.error\n"}, "start": 1639991189194, "stop": 1639991189299}], "start": 1639991189194, "stop": 1639991189554}