{"name": "test_refund", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'ResultBase' has no attribute 'erraor'", "trace": "self = <testcases.admin_test.test_refund_00001.TestAdminRefund object at 0x10c2b04a8>\n\n    def test_refund(self):\n        sql = \"select order_no from user_order where user_id in('1340') and\" \\\n              \" status not in(0,30,31,300) and real_price >= 0.1 limit 5 \"\n        data = db.select_db(sql)\n        logger.info(\"data===>{}\".format(data))\n        for i in range(len(data)):\n            logger.info(data[i][\"order_no\"])\n            order_no = data[i][\"order_no\"]\n            logger.info(\"*************** 开始执行用例 *************** /n\")\n            result = refund_admin(order_no)\n>           assert result.success is True, result.erraor\nE           AttributeError: type object 'ResultBase' has no attribute 'erraor'\n\ntest_refund_00001.py:19: AttributeError"}, "attachments": [{"name": "log", "source": "c3702343-2d41-450c-b26e-3eb6c654442d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "589def19-a7f6-4b9c-9d57-067626e2384a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "1bd52476-a1f8-4b47-8098-db0db4a07d80-attachment.txt", "type": "text/plain"}], "start": 1635909493968, "stop": 1635909494158, "uuid": "f9c8c5de-cc38-4eed-866e-e75bf6b6736e", "historyId": "a0a6875d0f15aa537f9fb7f8ef19067b", "testCaseId": "392cae74f4aea4f9774e5ed6ec104378", "fullName": "testcases.admin_test.test_refund_00001.TestAdminRefund#test_refund", "labels": [{"name": "parentSuite", "value": "testcases.admin_test"}, {"name": "suite", "value": "test_refund_00001"}, {"name": "subSuite", "value": "TestAdminRefund"}, {"name": "host", "value": "tongchunyan.local"}, {"name": "thread", "value": "39205-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.admin_test.test_refund_00001"}]}