{"name": "test_refund", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'ResultBase' has no attribute 'erraor'", "trace": "self = <testcases.admin_test.test_refund_00001.TestAdminRefund object at 0x10564b7f0>\n\n    def test_refund(self):\n        sql = \"select order_no from user_order where user_id = '1285' and\" \\\n              \" status not in(0,30,31,300) and real_price > 0.1 limit 3 \"\n        data = db.select_db(sql)\n        logger.info(\"data===>{}\".format(data))\n        for i in range(len(data)):\n            logger.info(data[i][\"order_no\"])\n            order_no = data[i][\"order_no\"]\n            logger.info(\"*************** 开始执行用例 *************** /n\")\n            result = refund_admin(order_no)\n>           assert result.success is True, result.erraor\nE           AttributeError: type object 'ResultBase' has no attribute 'erraor'\n\ntest_refund_00001.py:18: AttributeError"}, "attachments": [{"name": "log", "source": "5a390385-1a8c-4f1d-8032-0a3f509bbbfc-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "d006957e-8158-4604-9cc3-7412aa0868cc-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "77dc22eb-2bce-41a6-a73b-784f4a7f7531-attachment.txt", "type": "text/plain"}], "start": 1635336793836, "stop": 1635336794013, "uuid": "138915f0-11f8-45df-aa96-66cb8caaa1d9", "historyId": "a0a6875d0f15aa537f9fb7f8ef19067b", "testCaseId": "392cae74f4aea4f9774e5ed6ec104378", "fullName": "testcases.admin_test.test_refund_00001.TestAdminRefund#test_refund", "labels": [{"name": "parentSuite", "value": "testcases.admin_test"}, {"name": "suite", "value": "test_refund_00001"}, {"name": "subSuite", "value": "TestAdminRefund"}, {"name": "host", "value": "tongchunyan.local"}, {"name": "thread", "value": "73446-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.admin_test.test_refund_00001"}]}